/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-container': '#bfc6ff',
        'primary': '#ffffff',
        'on-tertiary': '#1b361b',
        'on-primary-fixed-variant': '#3d4d00',
        'tertiary-fixed-dim': '#aecfa8',
        'on-surface': '#e3e3df',
        'surface-tint': '#aed500',
        'inverse-surface': '#e3e3df',
        'surface-container-low': '#1a1c1a',
        'secondary-container': '#0136f1',
        'surface-container-lowest': '#0d0f0d',
        'secondary': '#bbc3ff',
        'on-secondary-fixed': '#000f5d',
        'on-tertiary-container': '#4e6c4b',
        'error-container': '#93000a',
        'primary-container': '#c7f300',
        'on-secondary-fixed-variant': '#002ccd',
        'tertiary-container': '#c9ecc3',
        'background': '#121412',
        'secondary-fixed-dim': '#bbc3ff',
        'surface-bright': '#383a37',
        'tertiary-fixed': '#c9ecc3',
        'on-surface-variant': '#c5c9ac',
        'on-primary': '#293500',
        'on-error': '#690005',
        'primary-fixed-dim': '#aed500',
        'on-tertiary-fixed': '#052108',
        'on-primary-container': '#576c00',
        'surface-container-highest': '#333533',
        'tertiary': '#ffffff',
        'surface-container': '#1e201e',
        'secondary-fixed': '#dee0ff',
        'surface-dim': '#121412',
        'on-secondary': '#001d93',
        'outline-variant': '#444933',
        'outline': '#8e9378',
        'on-background': '#e3e3df',
        'error': '#ffb4ab',
        'inverse-primary': '#526600',
        'surface-variant': '#333533',
        'surface-container-high': '#292a28',
        'surface': '#121412',
        'on-primary-fixed': '#171e00',
        'inverse-on-surface': '#2f312e',
        'primary-fixed': '#c7f300',
        'on-error-container': '#ffdad6',
        'on-tertiary-fixed-variant': '#314e30',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'margin-mobile': '16px',
        'panel-padding': '24px',
        unit: '4px',
        gutter: '16px',
        'margin-desktop': '32px',
      },
      fontFamily: {
        'headline-xl': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'data-display': ['"IBM Plex Mono"', 'monospace'],
        'data-sm': ['"IBM Plex Mono"', 'monospace'],
        'label-caps': ['"IBM Plex Mono"', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.2', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'data-display': ['14px', { lineHeight: '1.4', letterSpacing: '0.05em', fontWeight: '500' }],
        'data-sm': ['12px', { lineHeight: '1.2', letterSpacing: '0.02em', fontWeight: '400' }],
        'label-caps': ['10px', { lineHeight: '1', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      backgroundImage: {
        'technical-grid':
          'linear-gradient(to right, #444933 1px, transparent 1px), linear-gradient(to bottom, #444933 1px, transparent 1px)',
      },
      backgroundSize: {
        grid: '40px 40px',
      },
    },
  },
  plugins: [],
}
