/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        ink: '#0d0e10',
        bg: '#f4f1e6',
        surface: '#ffffff',
        'surface-2': '#efeadb',
        'surface-3': '#e3dcc7',
        rule: '#d6cfb9',
        'rule-soft': '#e8e3d0',
        text: '#0d0e10',
        'text-dim': '#4a4d57',
        'text-muted': '#8a8d96',
        cyan: '#0891b2',
        'cyan-deep': '#0e7490',
        amber: '#b45309',
        'amber-deep': '#7c2d12',
        danger: '#dc2626',
        'danger-deep': '#7f1d1d',
        ok: '#16a34a',
        'ok-deep': '#166534',
      },
      borderRadius: {
        none: '0',
        DEFAULT: '2px',
        sm: '2px',
        md: '4px',
        lg: '8px',
      },
      fontFamily: {
        display: ['"Bricolage Grotesque"', 'system-ui', 'sans-serif'],
        sans: ['Geist', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
      },
      fontSize: {
        'eyebrow': ['10px', { lineHeight: '1', letterSpacing: '0.18em', fontWeight: '500' }],
        'mono-xs': ['11px', { lineHeight: '1.3', letterSpacing: '0.04em' }],
        'mono-sm': ['12px', { lineHeight: '1.5', letterSpacing: '0.02em' }],
        'data':    ['13px', { lineHeight: '1.5', letterSpacing: '0.01em' }],
        'body':    ['14px', { lineHeight: '1.55' }],
        'lead':    ['18px', { lineHeight: '1.45', letterSpacing: '-0.005em' }],
        'h-sm':    ['28px', { lineHeight: '1.05', letterSpacing: '-0.025em', fontWeight: '500' }],
        'h-md':    ['44px', { lineHeight: '0.98', letterSpacing: '-0.035em', fontWeight: '500' }],
        'h-lg':    ['72px', { lineHeight: '0.92', letterSpacing: '-0.045em', fontWeight: '500' }],
        'metric':  ['56px', { lineHeight: '1',    letterSpacing: '-0.04em', fontWeight: '400' }],
      },
      keyframes: {
        scanline: {
          '0%':   { top: '-2%', opacity: '0' },
          '8%':   { opacity: '0.6' },
          '92%':  { opacity: '0.6' },
          '100%': { top: '102%', opacity: '0' },
        },
        flicker: {
          '0%, 96%, 100%': { opacity: '1' },
          '97%':           { opacity: '0.6' },
          '98%':           { opacity: '0.95' },
        },
        sweep: {
          '0%':   { transform: 'translateX(-100%)' },
          '100%': { transform: 'translateX(100%)' },
        },
        ping2: {
          '0%':   { transform: 'scale(1)',   opacity: '0.6' },
          '100%': { transform: 'scale(2.4)', opacity: '0' },
        },
        rise: {
          '0%':   { transform: 'translateY(8px)', opacity: '0' },
          '100%': { transform: 'translateY(0)',   opacity: '1' },
        },
      },
      animation: {
        scanline: 'scanline 5s linear infinite',
        flicker:  'flicker 6s linear infinite',
        sweep:    'sweep 2.4s ease-in-out infinite',
        ping2:    'ping2 1.6s cubic-bezier(0,0,0.2,1) infinite',
        rise:     'rise 0.5s cubic-bezier(0.16,1,0.3,1) both',
      },
    },
  },
  plugins: [],
}
